# Generated by Django 4.2.5 on 2023-09-09 09:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='user',
            field=models.CharField(default=django.utils.timezone.now, max_length=50, verbose_name='name'),
            preserve_default=False,
        ),
    ]
